"""add daily nutrition summary tables

Revision ID: 32455e768f0f
Revises: 7c19d8f37971
Create Date: 2024-12-11 14:41:22.022724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32455e768f0f'
down_revision: Union[str, None] = '7c19d8f37971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_nutrition_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('akg_fulfilled_count', sa.Integer(), nullable=False),
    sa.Column('akg_not_fulfilled_count', sa.Integer(), nullable=False),
    sa.Column('akg_fulfilled_mode', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_nutrition_summaries_id'), 'daily_nutrition_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_summaries_user_id'), 'daily_nutrition_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_nutrition_summaries_user_id'), table_name='daily_nutrition_summaries')
    op.drop_index(op.f('ix_daily_nutrition_summaries_id'), table_name='daily_nutrition_summaries')
    op.drop_table('daily_nutrition_summaries')
    # ### end Alembic commands ###
