"""add nutrition logs tables

Revision ID: 9fe868f8693b
Revises: 4ca9be842389
Create Date: 2024-12-11 05:41:57.206072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fe868f8693b'
down_revision: Union[str, None] = '4ca9be842389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_akg_fulfilled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_id'), 'nutrition_logs', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.create_table('nutrition_log_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('nutrition_log_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nutrition_log_id'], ['nutrition_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_log_foods_id'), 'nutrition_log_foods', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_log_foods_nutrition_log_id'), 'nutrition_log_foods', ['nutrition_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_log_foods_nutrition_log_id'), table_name='nutrition_log_foods')
    op.drop_index(op.f('ix_nutrition_log_foods_id'), table_name='nutrition_log_foods')
    op.drop_table('nutrition_log_foods')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_id'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    # ### end Alembic commands ###
