name: "Build and Deploy to Cloud Run"

on:
  push:
    branches: ["main", "develop"]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ vars.REGION}}
      GAR_NAME: ${{ vars.GAR_NAME }}
      SERVICE: ${{ vars.SERVICE }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332"

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2" # google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # BEGIN - Docker auth and build
      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.GAR_NAME }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Export gcloud related env variable
        run: export CLOUDSDK_PYTHON="/usr/bin/python3"

      - name: "Deploy to Cloud Run"
        # END - Docker auth and build
        #
        uses: "google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17" # google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"

          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.GAR_NAME }}:${{ github.sha }}"
